### ISSUE TITLE
How FFmpegKit ?

### ISSUE THREAD

**Issue by CMingTseng** [numq/compose-desktop-media-player#1]
Hello

I don’t know if I can refer to these two projects.

https://github.com/LandryNorris/FFmpegKitKotlinTestApp

https://github.com/LandryNorris/FFmpegKitKotlin

Wrap ffmpeg directly into the jvm part during the compilation phase?

Then you can run the desktop video player?

At present, you have to configure ffmpeg related files according to the platform.

I'm looking for a solution that can be used directly after compilation

THX

**Comment by numq** [comment]
Duplicate numq/Klarity#2
